### ISSUE TITLE
More downloading options

### ISSUE THREAD

**Issue by qige96** [uclnlp/EMAT#2]
Dear authors,

I saw that you put your checkpoints and other intermediate data on BaiduNetdisk. However, that's very poor product and I doubt whether non-Chinese users can use it properly, which may prevent people study and build their research on top of your foundation. I suggest that you provide more downloading options, like google drive, onedrive,or zenodo.

Best wishes,
Ricky

**Comment by pminervini** [comment]
I'm temporarily hosting everything on my personal website :) http://data.neuralnoise.com/EMAT/

**Comment by qige96** [comment]
Thanks a lot!
